# Generated by Django 2.2.14 on 2020-07-28 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        
            
            
            
            ]
