# Generated by Django 2.2.14 on 2020-07-28 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20200728_1820'),
    ]

    operations = [
    ]
