# Generated by Django 2.2.18 on 2021-07-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_auto_20210731_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_created',
            field=models.BooleanField(default=False),
        ),
    ]
