version: "3.9"
   
services:
  db:
    container_name: postgres_db
    image: postgres:13
    environment:
      - POSTGRES_DB=forge_devel
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - database-data:/var/lib/postgresql/data # persist data even if container shuts down
    ports:
      - "5432:5432"

  web:
    container_name: web
    build: .
    image: local/website
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=set_in_prod
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - POSTGRES_DB=forge_devel
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
    depends_on:
      - db



volumes:
    database-data:
      driver: local
