version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=forge_devel_octoprint
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - database-data:/var/lib/postgresql/data # persist data even if container shuts down
    ports:
      - "5432:5432"
    
  
  migration:
    build: .
    command: python manage.py migrate --noinput
    volumes:
      - .:/code
    depends_on:
      - db

  web:
    depends_on:
      - db
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - migration


volumes:
    database-data:
      driver: local