version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=forge_devel
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  web:
    depends_on:
      db:
        condition: service_healthy
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "5432:5432"
    depends_on:
      - db