# Generated by Django 3.2.5 on 2021-07-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('org_id', models.CharField(editable=False, max_length=6)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(default='', max_length=255)),
                ('default', models.BooleanField(default=False)),
                ('organization_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('membership_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('bill_member', models.BooleanField(default=True)),
                ('public', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
