# Generated by Django 3.2.5 on 2021-07-10 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='last_login',
        ),
    ]
