# Generated by Django 3.2.5 on 2021-07-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_management', '0007_machine_organization'),
        ('organization_management', '0005_alter_organization_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='machine_access',
            field=models.ManyToManyField(blank=True, null=True, related_name='useable_by', to='machine_management.Machine'),
        ),
    ]
