# Generated by Django 3.2.5 on 2021-07-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_management', '0006_alter_organization_machine_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='machine_access',
            field=models.ManyToManyField(blank=True, null=True, related_name='_organization_management_organization_machine_access_+', to='organization_management.Organization'),
        ),
    ]
