# Generated by Django 3.2.5 on 2021-07-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_management', '0009_alter_organization_machine_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='access',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
