# Generated by Django 3.2.6 on 2021-08-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_management', '0012_auto_20210807_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='machine_access',
            field=models.ManyToManyField(blank=True, null=True, related_name='shared_organizations', to='organization_management.Organization'),
        ),
    ]
