# Generated by Django 2.2.17 on 2021-01-14 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status_message', models.CharField(default='In Progress.', max_length=255)),
                ('complete', models.BooleanField(default=False)),
                ('error', models.BooleanField(default=False)),
                ('file_id', models.CharField(blank=True, default=None, max_length=36, null=True)),
                ('layer_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToolTemperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
                ('temperature', models.FloatField()),
                ('temperature_goal', models.FloatField()),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_management.JobInformation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocationInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('layer', models.IntegerField()),
                ('max_layer', models.IntegerField()),
                ('z_location', models.FloatField()),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_management.JobInformation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
