# Generated by Django 2.2.17 on 2021-01-14 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine_management', '0001_initial'),
        ('data_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinformation',
            name='machine',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='machine_management.Machine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobinformation',
            name='usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machine_management.Usage'),
        ),
    ]
