# Generated by Django 2.2.18 on 2021-07-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0002_alter_jobinformation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinformation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
