# Generated by Django 3.2.17 on 2023-02-05 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('unit', models.CharField(max_length=255)),
                ('cost_per', models.DecimalField(decimal_places=2, max_digits=5)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QuantityResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='n/a', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('cost_override', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(blank=True, max_length=255)),
                ('shape', models.CharField(blank=True, max_length=255)),
                ('weight', models.CharField(blank=True, max_length=255)),
                ('quantity', models.BigIntegerField()),
                ('resource_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_management.resourcecategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndividualResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='n/a', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('cost_override', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(blank=True, max_length=255)),
                ('shape', models.CharField(blank=True, max_length=255)),
                ('weight', models.CharField(blank=True, max_length=255)),
                ('resource_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_management.resourcecategory')),
                ('resource_condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_management.resourcecondition')),
                ('usable',models.BooleanField(default=True))
            ],
            options={
                'abstract': False,
            },
        ),
    ]
