# Generated by Django 2.2.6 on 2019-10-26 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=255)),
                ('in_use', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MachineSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('cost_per', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rin', models.PositiveIntegerField(blank=True, default=0)),
                ('gender', models.CharField(blank=True, default='', max_length=255)),
                ('major', models.CharField(blank=True, default='', max_length=255)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_class', models.BooleanField()),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('planned_duration', models.DurationField()),
                ('fail_time', models.DateTimeField(null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('complete', models.BooleanField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine_usage.Machine')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine_usage.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='SlotUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=5, max_digits=10)),
                ('machine_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine_usage.MachineSlot')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine_usage.Resource')),
                ('usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine_usage.Usage')),
            ],
        ),
        migrations.AddField(
            model_name='machineslot',
            name='allowed_resources',
            field=models.ManyToManyField(to='machine_usage.Resource'),
        ),
        migrations.AddField(
            model_name='machineslot',
            name='machine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine_usage.MachineType'),
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine_usage.MachineType'),
        ),
    ]
