# Generated by Django 2.2.6 on 2019-10-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_usage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinetype',
            name='machine_category',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
