# Generated by Django 2.2.6 on 2019-11-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_usage', '0003_auto_20191111_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='outstanding_balance',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verified_email',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
