# Generated by Django 2.2.7 on 2019-11-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_usage', '0004_auto_20191111_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verification_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
