# Generated by Django 2.2.6 on 2019-11-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_usage', '0004_auto_20191111_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='status_message',
            field=models.CharField(default='', max_length=255),
        ),
    ]
