# Generated by Django 2.2.6 on 2019-11-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_usage', '0005_auto_20191112_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='status_message',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
