# Generated by Django 2.2.7 on 2019-11-16 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine_usage', '0005_userprofile_verification_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='verification_token',
            new_name='user_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='verified_email',
        ),
    ]
