# Generated by Django 2.2.7 on 2019-11-28 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine_usage', '0006_auto_20191116_0150'),
        ('machine_usage', '0006_auto_20191112_1800'),
    ]

    operations = [
    ]
