# Generated by Django 2.2.7 on 2019-11-28 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine_usage', '0007_merge_20191127_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_token',
            new_name='email_verification_token',
        ),
    ]
