# Generated by Django 2.2.7 on 2020-01-05 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine_usage', '0010_auto_20191128_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usage',
            name='fail_time',
        ),
        migrations.RemoveField(
            model_name='usage',
            name='planned_duration',
        ),
        migrations.AddField(
            model_name='machine',
            name='current_job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_machine', to='machine_usage.Usage'),
        ),
        migrations.AddField(
            model_name='usage',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usage',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usage',
            name='for_class',
            field=models.BooleanField(default=False),
        ),
    ]
