# Generated by Django 2.2.8 on 2020-01-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_usage', '0011_auto_20200105_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
