# Generated by Django 2.2.8 on 2020-01-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_usage', '0012_auto_20200105_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinetype',
            name='hourly_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
