# Generated by Django 2.2.8 on 2020-01-19 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_usage', '0014_machinetype_data_entry_after_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinetype',
            name='usage_policy',
            field=models.CharField(default='', max_length=4096),
        ),
    ]
