# Generated by Django 2.2.8 on 2020-01-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_usage', '0015_machinetype_usage_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='cost_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usage',
            name='cost_override_reason',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='usage',
            name='is_reprint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usage',
            name='overridden_cost',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='usage',
            name='own_material',
            field=models.BooleanField(default=False),
        ),
    ]
