# Generated by Django 2.2.8 on 2020-01-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_usage', '0016_auto_20200120_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='clear_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
