# Generated by Django 2.2.8 on 2020-01-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_usage', '0018_auto_20200120_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='failed',
            field=models.BooleanField(default=False),
        ),
    ]
