# Generated by Django 2.2.8 on 2020-01-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_usage', '0020_auto_20200121_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='overridden_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
