# Generated by Django 2.2.8 on 2020-01-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_usage', '0022_userprofile_anonymous_usages'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='entertainment_mode',
            field=models.BooleanField(default=False),
        ),
    ]
