# Generated by Django 2.2.14 on 2020-08-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_usage', '0024_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=models.SET(None), to='machine_usage.Semester'),
            preserve_default=False,
        ),
    ]
