# Generated by Django 2.2.14 on 2020-08-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_usage', '0025_usage_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
