# Generated by Django 2.2 on 2020-10-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='machine_id',
        ),
        migrations.AddField(
            model_name='machine',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
