# Generated by Django 2.2.14 on 2021-01-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinetype',
            name='usage_policy',
            field=models.CharField(blank=True, default='', max_length=4096),
        ),
    ]
