# Generated by Django 2.2.4 on 2020-10-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_management', '0002_auto_20201001_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tooltemperature',
            name='tool_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
