# Generated by Django 2.2.4 on 2020-10-02 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_management', '0003_auto_20201001_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='file_id',
            field=models.CharField(blank=True, default=None, max_length=36, null=True),
        ),
    ]
