# Generated by Django 2.2.14 on 2021-04-02 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '__first__'),
        ('machine_management', '0004_auto_20201115_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='current_print_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_job', to='data_management.JobInformation'),
        ),
        migrations.AddField(
            model_name='usage',
            name='current_print_information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job', to='data_management.JobInformation'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='current_job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_usage', to='machine_management.Usage'),
        ),
        migrations.AlterField(
            model_name='machinetype',
            name='usage_policy',
            field=models.CharField(blank=True, default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='usage',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='business.Semester'),
        ),
        migrations.AlterField(
            model_name='usage',
            name='userprofile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.UserProfile'),
        ),
    ]
