# Generated by Django 2.2.4 on 2020-10-03 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine_management', '0005_auto_20201002_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='current_job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_usage', to='machine_management.Usage'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='current_print_information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_job', to='machine_management.JobInformation'),
        ),
    ]
