# Generated by Django 3.2.7 on 2021-09-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_management', '0006_auto_20210709_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='personal_material',
            field=models.BooleanField(default=False),
        ),
    ]
