# Generated by Django 2.2.4 on 2020-10-03 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine_management', '0006_auto_20201003_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='current_print_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_job', to='machine_management.JobInformation'),
        ),
    ]
