# Generated by Django 3.2.5 on 2021-07-11 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_management', '0002_remove_organization_last_login'),
        ('machine_management', '0006_auto_20210709_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='organization_management.organization'),
        ),
    ]
