# Generated by Django 3.2.5 on 2021-07-19 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_management', '0009_alter_organization_machine_access'),
        ('machine_management', '0007_machine_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usage',
            name='for_class',
        ),
        migrations.AddField(
            model_name='usage',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization_management.organization'),
        ),
    ]
