# Generated by Django 3.2.7 on 2021-09-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_management', '0007_machine_personal_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='personal_material',
        ),
        migrations.AddField(
            model_name='machine',
            name='personal_material_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
