# Generated by Django 2.2.14 on 2020-11-23 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine_management', '0004_auto_20201115_1315'),
        ('machine_management', '0008_auto_20201013_2314'),
    ]

    operations = [
    ]
