# Generated by Django 3.2.17 on 2023-02-05 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '__first__'),
        ('machine_management', '0009_alter_usage_current_print_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineslot',
            name='allowed_resources',
            field=models.ManyToManyField(to='inventory_management.ResourceCategory'),
        ),
        migrations.AlterField(
            model_name='slotusage',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.resourcecategory'),
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
