# Generated by Django 3.2.10 on 2021-12-13 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine_management', '0009_alter_usage_current_print_information'),
        ('machine_management', '0011_auto_20210807_2135'),
    ]

    operations = [
    ]
