# Generated by Django 3.2.10 on 2021-12-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_semester_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='buisness_message',
            field=models.TextField(default=''),
        ),
    ]
