# Generated by Django 3.2.10 on 2021-12-13 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_semester_buisness_message'),
        ('business', '0004_alter_semester_id'),
    ]

    operations = [
    ]
