# Generated by Django 2.2 on 2020-09-30 23:57

import apis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API_Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('key', models.CharField(default=apis.models.generate_key, max_length=15)),
            ],
        ),
    ]
