# Generated by Django 2.2 on 2020-10-01 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='API_Key',
            new_name='Key',
        ),
    ]
