# Generated by Django 3.2.6 on 2021-08-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_auto_20210731_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
